### ISSUE TITLE
error on ubuntu

### ISSUE THREAD

**Issue by wangbourne** [apostrophecms/stagecoach#20]
It's ok on centos. However, i got an problem on digitalocean ubuntu:

![image](https://cloud.githubusercontent.com/assets/2090084/18300642/4d7a207a-750e-11e6-8d13-52a97630136b.png)

my question is:
1. does sc-deploy support to show details log when deployment? or where can i find logs?
2. which source and version of npm/node I should install in ubuntu: Distro-Stable Version or PPA?  (https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server)

**Comment by abea** [comment]
There aren't independent logs from the `sc-deploy` script, no. 

Out of date. Apologies for the delay.
