### ISSUE TITLE
Possibly update to support Windows deployments.

### ISSUE THREAD

**Issue by rwatts3** [apostrophecms/stagecoach#21]
Greetings, 

I've written a few cli tools using an npm module and shelljs to support cross platform environments.
I'm wondering if I submit a pull request would this be something worth looking into to allow Windows users, and other platform users the ability to deploy their applications .

**Comment by abea** [comment]
I realize this is very old at this point, but we'd be happy to review a PR. Though with Linux on Windows maybe this is no longer an issue. Closing for now given the OP date.
